name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    needs: build

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.build.outputs.pages-url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v4
        id: build
